version: 0.2

phases:
  pre_build:
    commands:
      - echo Updating image URI
      - sed -i "s|<IMAGE_URI>|$REPOSITORY_URI:$IMAGE_TAG|g" taskdef.json

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
